### ISSUE TITLE
OP CODE bug fix for RTS, LEA, BEA, and JSR

### ISSUE THREAD

**Issue by ghost** [aburkhalter512/css422#42]
Terry, it seems like you already have OC_NO_SIZE mask,
which should be used for LEA, BEQ, and JSR, but your current version of code is returning OC_LONG_SIZE mask instead.
Also, there're some problem with RTS; PROCESS_OC does not return any stack value for RTS.
It will be nice if you fix these problems.

**Comment by Turray** [comment]
Refer to #24 and #25 about the sizing issues with JSR and LEA. BEQ, as well as all branching instructions, have sizing. Refer to page 129 for more information. RTS does return 001F, which is RTS with no size, no word count, and no EA count. The only issue that I can see is that the byte information for 001F is in consecutive words rather than contained in one word like the rest of my return values. I have created an issue, and will resolve it with my next push. See #43 for more information.

**Comment by Turray** [comment]
The bug with RTS has been fixed. See #43 for more information.

**Comment by Turray** [comment]
What needs to happen is either I need to change the size to OC_NO_SIZE before returning, or you need to check for JSR or LEA and not print the size. I may be able to handle it, but I'm leaving it until I have all Opcodes implemented.

**Comment by ghost** [comment]
I just wired my system little bit differently, and handled this issue.
Case closed.
