### ISSUE TITLE
OP Decoder - Error with couple instructions

### ISSUE THREAD

**Issue by ghost** [aburkhalter512/css422#46]
Single data instructions are distorting the following one instruction.
For example, if there's Instruction BEQ and ADD, 4B40 is stacked for OPCODE, which supposed to be 0A40.
Also, there are issue with SUBI; this one stacks two same set of data with same size.

**Comment by Turray** [comment]
There was an issue where the code to set the starting address (A2) was deleted. Please see the comment in 492d343905ff16a6cb1ab88dc9acd3e06c80ef07. That code has to be there. If it's not, then no instructions can be decoded. Once we have a proper instruction input, then that code can be safely deleted. Until then, please leave it.

Now that the code is back in place, BEQ instructions can once again we decoded properly.

I'm not sure what the problem is with decoding BEQ and then ADD. The Opcode Decoder properly returns the correct values for each singular case, so I don't think that's the problem. Must be something in I/O.

The issue with SUBI has been resolved. There was a minor error in OC_TWO_EA that always set the data offset for the destination to 0, so the data returned for the destination would always be the same as the source destination.

**Comment by Turray** [comment]
I want to verify the return values of the Opcode Decoder:

Input: BEQ 031E (This wouldn't assemble, but conceptually we are branching forward with a displacement of 031E).
Opcode Decoder Return Value: 0989 05 05 00004320 (Correct; assuming the instruction for BEQ was at address $4000.)
I/O Output: BEQ $4320 (Correct)

Input: ADD.B $5000, D1
Opcode Decoder Return Value: 0A40 03 04 5000 01 08 (Correct)
I/O Output: ADD.B $00,D1 (Incorrect; the source is incorrect, but the destination is.)

Input: SUBI.L #777, $09381764
Opcode Decoder Return Value: 22E2 05 07 00000309 05 05 09381764 (Correct)
I/O Output: SUBI.L #$0309,$00000309 (Incorrect; the source is correct, but the destination isn't.)
